# Generated by Django 4.2.29 on 2026-03-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ingredient',
            new_name='ingredients_name_dd17d9_idx',
            old_name='ingredients_name_idx',
        ),
    ]
