# Generated by Django 4.2.29 on 2026-03-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_rename_ingredients_name_idx_ingredients_name_dd17d9_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_a', models.CharField(help_text='First ingredient name or keyword', max_length=200)),
                ('ingredient_b', models.CharField(help_text='Second ingredient name or keyword', max_length=200)),
                ('severity', models.CharField(choices=[('avoid', 'Avoid together'), ('caution', 'Use with caution'), ('time', 'Use at different times')], default='caution', max_length=10)),
                ('reason', models.TextField()),
                ('safe_alternative', models.TextField(blank=True, help_text='What to do instead')),
            ],
            options={
                'unique_together': {('ingredient_a', 'ingredient_b')},
            },
        ),
    ]
