# Generated by Django 4.2.29 on 2026-03-14 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkinProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(choices=[('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('normal', 'Normal'), ('sensitive', 'Sensitive')], max_length=20)),
                ('climate', models.CharField(default='temperate', max_length=50)),
                ('age_range', models.CharField(default='25-34', max_length=20)),
                ('fitzpatrick', models.IntegerField(default=2)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concerns', models.ManyToManyField(blank=True, to='profiles.skinconcern')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
