# Generated by Django 4.2.29 on 2026-03-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_india_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_brand_4bfaa4_idx',
            old_name='products_pr_brand_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_14b9c0_idx',
            old_name='products_pr_category_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_price_9b1a5f_idx',
            old_name='products_pr_price_idx',
        ),
        migrations.RenameIndex(
            model_name='similaritycache',
            new_name='products_si_product_b43989_idx',
            old_name='products_si_product_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_ayurvedic',
        ),
        migrations.RemoveField(
            model_name='product',
            name='made_in_india',
        ),
    ]
