# Generated by Django 4.2.29 on 2026-03-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_products_pr_brand_idx_products_pr_brand_4bfaa4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='INR', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='is_ayurvedic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='made_in_india',
            field=models.BooleanField(default=False),
        ),
    ]
