# Generated by Django 4.2.29 on 2026-03-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_currency_product_is_ayurvedic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_url',
            field=models.URLField(blank=True, help_text='Direct link to purchase this product (e.g. Amazon, Nykaa, Sephora)', null=True),
        ),
    ]
