# Generated by Django 4.2.29 on 2026-03-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_purchase_url_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
