# Generated by Django 4.2.29 on 2026-03-14 15:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_pricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviewAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('positive_pct', models.FloatField(blank=True, null=True)),
                ('neutral_pct', models.FloatField(blank=True, null=True)),
                ('negative_pct', models.FloatField(blank=True, null=True)),
                ('avg_hydration', models.FloatField(blank=True, null=True)),
                ('avg_texture', models.FloatField(blank=True, null=True)),
                ('avg_scent', models.FloatField(blank=True, null=True)),
                ('avg_irritation', models.FloatField(blank=True, null=True)),
                ('avg_efficacy', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_aggregate', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='Anonymous', max_length=120)),
                ('body', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('source', models.CharField(blank=True, help_text='e.g. nykaa, purplle, manual', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment_label', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20)),
                ('sentiment_score', models.FloatField(blank=True, help_text='Confidence 0–1 for the predicted label', null=True)),
                ('analysed', models.BooleanField(default=False)),
                ('aspect_hydration', models.FloatField(blank=True, null=True)),
                ('aspect_texture', models.FloatField(blank=True, null=True)),
                ('aspect_scent', models.FloatField(blank=True, null=True)),
                ('aspect_irritation', models.FloatField(blank=True, null=True)),
                ('aspect_efficacy', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
